name: Add non-bug issues to project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/mathjoha/projects/2/
          github-token: ${{ secrets.PROJECT_TOKEN }}
          labeled: bug
          label-operator: NOT
